
buildscript {
    ext.kotlin_version = '1.9.25'
    ext {
        activity_compose_version = '1.9.2'
        hilt_navigation_compose_version = '1.0.0'
        navigation_compose_version = '2.8.2'

        concurrent_futures_version = '1.2.0'
        health_connect_version = '1.1.0-alpha12'
        lifecycle_version = '2.8.6'
    }
    repositories {
        google()
        mavenCentral()
        maven { url "https://androidx.dev/storage/health-connect/m2repository" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "com.diffplug.spotless" version "6.25.0"
}

subprojects {
    apply plugin: "com.diffplug.spotless"
    spotless {
        kotlin {
            target "**/*.kt"
            targetExclude("$buildDir/**/*.kt")
            targetExclude("bin/**/*.kt")

            ktlint("0.41.0").userData(["max_line_length" : "100"])
            trimTrailingWhitespace()
            indentWithSpaces()
            endWithNewline()
            licenseHeaderFile rootProject.file("spotless/copyright.txt")
        }
    }
}