
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

apply plugin: 'kotlin-kapt'

android {
    compileSdk 35

    defaultConfig {
        applicationId "com.zihanwang.myhealth"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.majorVersion
        freeCompilerArgs = ['-Xjvm-default=all-compatibility']
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    namespace 'com.zihanwang.myhealth'
}
def health_connect_version = "1.1.0-alpha12"
def lifecycle_version = "2.8.4"
def navigation_compose_version = "2.8.0"
def concurrent_futures_version = "1.1.0"
def activity_compose_version = "1.9.2"

dependencies {

    def composeBom = platform('androidx.compose:compose-bom:2024.09.03')
    implementation(composeBom)

    // For Health Connect
    implementation "androidx.health.connect:connect-client:$health_connect_version"

    // Fix permissions issue until 1.1.0-alpha02
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.core:core-ktx:1.13.1"

    // For viewmodel support
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycle_version"

    // Navigation
    implementation "androidx.navigation:navigation-compose:$navigation_compose_version"

    // To bridge between ListenableFuture and suspend functions
    implementation "androidx.concurrent:concurrent-futures-ktx:$concurrent_futures_version"

    // Icons
    implementation "androidx.compose.material:material-icons-extended"
    implementation "com.google.accompanist:accompanist-drawablepainter:0.36.0"

    implementation "androidx.compose.ui:ui"
    implementation "androidx.compose.material:material"
    implementation "androidx.compose.ui:ui-tooling-preview"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.activity:activity-compose:$activity_compose_version"

    debugImplementation "androidx.compose.ui:ui-tooling"

    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.2"
    implementation "com.google.accompanist:accompanist-systemuicontroller:0.36.0"

    // Room
    implementation "androidx.room:room-runtime:2.6.1"
    kapt "androidx.room:room-compiler:2.6.1"
    implementation "androidx.room:room-ktx:2.6.1"

    // Lifecycle + ViewModel (+ Compose VM interop)
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.8.4"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.8.4"

    // Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"

    // Jetpack DataStore (Preferences)
    implementation "androidx.datastore:datastore-preferences:1.1.1"

    implementation "androidx.compose.ui:ui-text"

    implementation("com.squareup.retrofit2:retrofit:2.9.0")
    implementation("com.squareup.retrofit2:converter-gson:2.9.0")
    implementation("com.google.code.gson:gson:2.10.1")

    // Unit testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

}


